name: Codestyle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: go fmt
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then gofmt -s -d; exit 1; fi

      - name: go test
        run: go test ./... -coverprofile=coverage.out -vet=off -v

      - name: go vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.3.2
        with:
          args: --timeout=5m
